# Generated by Django 3.2 on 2021-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('success', 'success'), ('warning', 'warning'), ('failure', 'failure')], max_length=16)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
